### ISSUE TITLE
Fix data quality issues discovered during schema creation

### ISSUE THREAD

**Issue by bendnorman** [deployment-gap-model-education-fund/deployment-gap-model#239]
Adding SQLAlchemy schemas revealed some small data quality issues. 

**Data Warehouse Issues:**  See discussion in [this pr](https://github.com/down-ballot-climate-partners/deployment-gap-model/pull/230).

**Data Mart Issues:**
- [x] `proposed_power_dash_existing_plants`: `county_id_fips`  is a part of the pk but is missing 9 values.
- [x] `proposed_power_dash_proposed_plants`: `county_id_fips` and `resource` are both a part of the pk but missing 9 values.
- [x] `co2_dashboard`: Should be a part of the pk but is missing one value.

**Comment by TrentonBush** [comment]
These tables are obsolete; were removed in #250
