### ISSUE TITLE
Plan Higher Frequency AirTable Updates

### ISSUE THREAD

**Issue by TrentonBush** [deployment-gap-model-education-fund/deployment-gap-model#359]
Scope out AirByte or other tools and estimate cost/benefit of automating AirTable data integration at a more frequent cadence. Also, look into the feasibility of using webhooks to kick off update jobs. Then instead of doing scheduled (nightly) builds that have 24 hour delays from AirTable update to BigQuery update, the delay could be reduced to something like 1 hour or less.

**Comment by bendnorman** [comment]
The design doc has been approved. Here is the first [issue](https://github.com/deployment-gap-model-education-fund/deployment-gap-model/issues/365)
