### ISSUE TITLE
Develop Tableau dev/prod best practices

### ISSUE THREAD

**Issue by bendnorman** [deployment-gap-model-education-fund/deployment-gap-model#85]
Our rapid changes to the ETL and dashboards highlighted the need for a more standard development and production cycle for this project. 

Currently, each dashboard is pointing at one BigQuery instance with a live connection. Ideally, data is only loaded to BQ from our main branch but it seems like folks want to make smaller changes to the data as they are dashboarding. 

I'm concerned we will have a couple of dashboards working well / in a production state, then break them all by updating the BQ data from an untested branch. 

What are best practices for dev/prod with Tableau? We have 3 things we need to version control: our code, data and dashboards.

**Comment by TrentonBush** [comment]
We are transitioning away from Tableau. No longer needed.
