### ISSUE TITLE
Create data validation tests

### ISSUE THREAD

**Issue by bendnorman** [deployment-gap-model-education-fund/deployment-gap-model#97]
We currently don't have any data validation tests. This has led to Matt finding data quality issues before us :/ 

PUDL runs data validation using database constraints and more custom validation with pytest. 

I propose we flesh out some more validation checks using pandera or great expectations. We are already using Pandera and it is a little more light weight.

**Comment by TrentonBush** [comment]
Redundant with #136 and partly addressed by PR #284
